'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Products',
      [
        {
          name: "Ades de Almendra",
          price: 1500,
          discount: 0,
          description: "Ades de Almendra sabor vainilla",
          brandId: 3,
          categoryId: 1,
          sectionId: 1,
          image:"ades.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Alfajor Sin Culpa",
          price: 600,
          discount: 0,
          description: "Alfajor sin culpa sabor frutilla",
          brandId: 3,
          categoryId: 3,
          sectionId: 1,
          image:"alfajor-1.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Alfajor ceral",
          price: 700,
          discount: 0,
          description: "Alfajor Ceral dulche de leche",
          brandId: 1,
          categoryId: 3,
          sectionId: 1,
          image:"alfajor-2.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Alfajor Vegano",
          price: 850,
          discount: 0,
          description: "Alfajor vegano 60gr",
          brandId: 1,
          categoryId: 3,
          sectionId: 1,
          image:"alfajor-3.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Te Boldo",
          price: 1500,
          discount: 0,
          description: "Te Boldo marca taragui",
          brandId: 1,
          categoryId: 1,
          sectionId: 1,
          image:"boldo.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Arandano",
          price: 1500,
          discount: 10,
          description: "Alfajor choco arroz sabor chocolate",
          brandId: 1,
          categoryId: 1,
          sectionId: 2,
          image:"arandano-jugo.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Arroz",
          price: 1400,
          discount: 0,
          description: "Arroz blanco cultivo ecologico 1kg ",
          brandId: 1,
          categoryId: 4,
          sectionId: 1,
          image:"arroz.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "galletita de avena y limon",
          price: 1650,
          discount: 0,
          description: "Galletitas integral de avena y limon",
          brandId: 1,
          categoryId: 3,
          sectionId: 1,
          image:"galletita.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Vitamina b12",
          price: 3750,
          discount: 10,
          description: "Vitamina b12 en compimidos",
          brandId: 1,
          categoryId: 5,
          sectionId: 2,
          image:"b12.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Biota Vitamina",
          price: 4550,
          discount: 25,
          description: "Vitamina b12 en compimidos",
          brandId: 1,
          categoryId: 5,
          sectionId: 2,
          image:"biosa.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Choco Arroz",
          price: 750,
          discount: 0,
          description: "Choco arroz de chocolate",
          brandId: 1,
          categoryId: 3,
          sectionId: 1,
          image:"b12.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Aceite de coco",
          price: 3750,
          discount: 5,
          description: "Aceite de coco neutro",
          brandId: 1,
          categoryId: 2,
          sectionId: 2,
          image:"coco.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Galletitas rustica",
          price: 1750,
          discount: 10,
          description: "Galletitas rusticas integrales 200gr",
          brandId: 1,
          categoryId: 5,
          sectionId: 1,
          image:"cokies.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Desodorante natural",
          price: 2750,
          discount: 15,
          description: "Desodorante natural herbal Senlida Botanica",
          brandId: 1,
          categoryId: 2,
          sectionId: 2,
          image:"desodorante.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Jugo Arandano el bolso",
          price: 1750,
          discount: 10,
          description: "jugo de arandano el bolson 1lt",
          brandId: 1,
          categoryId: 1,
          sectionId: 2,
          image:"bolson.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Galletita la zaranda",
          price: 1750,
          discount: 20,
          description: "Galletitas veganas la zaranda",
          brandId: 1,
          categoryId: 3,
          sectionId: 2,
          image:"galletita.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Infusion naranja",
          price: 350,
          discount: 0,
          description: "Sobresito infusion de naranja Orballo",
          brandId: 1,
          categoryId: 1,
          sectionId: 1,
          image:"infusion-1.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Infusion Hinojo",
          price: 350,
          discount: 0,
          description: "Sobresito infusion de Hinojo Orballo",
          brandId: 1,
          categoryId: 1,
          sectionId: 1,
          image:"infusion-2.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sobresitos de infusiones",
          price: 350,
          discount: 0,
          description: "Sobresito de infusion surtidos",
          brandId: 1,
          categoryId: 1,
          sectionId: 1,
          image:"infusiones.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        }
        ,
        {
          name: "lenteja",
          price: 1550,
          discount: 0,
          description: "Lenteja por kilo",
          brandId: 1,
          categoryId: 4,
          sectionId: 1,
          image:"lenteja.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Jugo naranja Detox",
          price: 1350,
          discount: 10,
          description: "jugo de naranja Detox",
          brandId: 1,
          categoryId: 1,
          sectionId: 2,
          image:"naranja.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Pancake",
          price: 2350,
          discount: 30,
          description: "Pancakes lista para calentar",
          brandId: 1,
          categoryId: 3,
          sectionId: 2,
          image:"pancake.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Pasas de uva",
          price: 2350,
          discount: 40,
          description: "Pasa de uva",
          brandId: 1,
          categoryId: 3,
          sectionId: 2,
          image:"pasas.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        }
        ,
        {
          name: "Poroto",
          price: 1350,
          discount: 0,
          description: "Poroto negro por kilo",
          brandId: 1,
          categoryId: 4,
          sectionId: 1,
          image:"poroto.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Crema karite y coco",
          price: 2350,
          discount: 10,
          description: "Crema karite y coco Terra",
          brandId: 1,
          categoryId: 2,
          sectionId: 2,
          image:"terra.jpeg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "harina de Trigo",
          price: 2000,
          discount: 10,
          description: "Harina de trigo por kilo",
          brandId: 1,
          categoryId: 4,
          sectionId: 2,
          image:"trigo.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Cosmetica Veganis",
          price: 3500,
          discount: 10,
          description: "Acondicionador Veganis 750ml",
          brandId: 1,
          categoryId: 2,
          sectionId: 2,
          image:"veganis.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Cosmetica Veganis",
          price: 5500,
          discount: 10,
          description: "gotas Veganis 100ml",
          brandId: 1,
          categoryId: 2,
          sectionId: 2,
          image:"veganis-2.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Vitamina b50",
          price: 10500,
          discount: 10,
          description: "Vitamina b50 en compirmidos 50unidades",
          brandId: 1,
          categoryId: 5,
          sectionId: 2,
          image:"vitaminab50.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Vitamina C",
          price: 10500,
          discount: 15,
          description: "Vitamina C en compirmidos 50unidades",
          brandId: 1,
          categoryId: 5,
          sectionId: 2,
          image:"vitaminaC.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Vitamina ZINC",
          price: 10500,
          discount: 10,
          description: "Vitamina ZINC en compirmidos 50unidades",
          brandId: 1,
          categoryId: 5,
          sectionId: 2,
          image:"zinc.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Products', null, {});
  }
};